on:
  workflow_dispatch:
    inputs:
      application_name:
        required: true
        description: name of the go app to create
        type: string
      # port_payload:
      #   required: true
      #   description: "Port's payload, including details for who triggered the action an general context (blueprint, run id, etc...)"
      #   type: string
jobs:
  testjob:
    runs-on: ubuntu-latest
    steps:
      - name: "create app repository"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh repo create ${{ inputs.application_name }} --public -p go-template

